#
# Macro file for the initialization phase of "exampleN06.cc"
# when running in interactive mode
#
# Sets some default verbose
#
/control/verbose 0
/run/verbose 2
/tracking/verbose 2
/hits/verbose 1
#
# create empty scene
#
/vis/scene/create
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#
###/vis/open DAWNFILE
/vis/open HepRepFile
#
/vis/viewer/zoom 1.5
/vis/viewer/flush
#
# for drawing the tracks
# Draw trajectories at end of event, showing trajectory points as
# markers of size 2 pixels
/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => storeTrajectory 0)
#
/vis/scene/endOfEventAction accumulate
#
# Refresh ready for run
/vis/viewer/refresh
#
# Now ready for /run/beamOn.

/gun/particle opticalphoton
/gun/energy 0.1 eV
/gun/position 0 0 0 cm
/gun/direction 1 0 0.001
/run/beamOn 1

