# ----------------
# Verbose settings
# ----------------
/control/verbose 2
/run/verbose 2
#/tracking/verbose 2

# HepRepFile diriver
/vis/open HepRepFile

# OpenGL drivers
#/vis/open OGLIX
#/vis/open OGLIXm

# Add world volume
/vis/drawVolume

# Visualise geometry
/vis/viewer/flush

# Set camera angle for OGLIXm driver
/vis/viewer/set/viewpointThetaPhi 70 60
/vis/viewer/set/hiddenEdge true

# Add trajectories to the visualization.
/vis/scene/add/trajectories

# HandsOn4: add hits to scene
/vis/scene/add/hits

# Accumulate multiple events in one picture.
#/vis/scene/endOfEventAction accumulate

# Trajectory colouring scheme
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/set -1 blue
/vis/modeling/trajectories/drawByCharge-0/set 1 green
/vis/modeling/trajectories/drawByCharge-0/set 0 red

#HandsOn4: change primary particle energy
/gun/energy 500 MeV
/gun/particle e-
/gun/position 10 0 0 m
/gun/direction 1 0 0
/run/beamOn 1



